"""games table

Revision ID: 2bf05a1b2d70
Revises: 312ea1a7bf5c
Create Date: 2024-03-16 13:23:14.278859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf05a1b2d70'
down_revision = '312ea1a7bf5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('game_title', sa.String(length=64), nullable=True),
    sa.Column('handheld', sa.Boolean(), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('multiplatform', sa.Boolean(), nullable=True),
    sa.Column('genres', sa.String(length=64), nullable=True),
    sa.Column('licensed', sa.Boolean(), nullable=True),
    sa.Column('publishers', sa.String(length=64), nullable=True),
    sa.Column('sequel', sa.Boolean(), nullable=True),
    sa.Column('review_score', sa.Integer(), nullable=True),
    sa.Column('sales', sa.Float(), nullable=True),
    sa.Column('used_price', sa.Float(), nullable=True),
    sa.Column('console', sa.String(length=64), nullable=True),
    sa.Column('age_rating', sa.String(length=64), nullable=True),
    sa.Column('re_release', sa.Boolean(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('average_time', sa.Float(), nullable=True),
    sa.Column('slowest_time', sa.Float(), nullable=True),
    sa.Column('median_time', sa.Float(), nullable=True),
    sa.Column('finish_number', sa.Integer(), nullable=True),
    sa.Column('fastest_time', sa.Float(), nullable=True),
    sa.Column('average_completion', sa.Float(), nullable=True),
    sa.Column('slowest_completion', sa.Float(), nullable=True),
    sa.Column('median_completion', sa.Float(), nullable=True),
    sa.Column('completion_number', sa.Integer(), nullable=True),
    sa.Column('fastest_completion', sa.Float(), nullable=True),
    sa.Column('average_extras', sa.Float(), nullable=True),
    sa.Column('slowest_extras', sa.Float(), nullable=True),
    sa.Column('median_extras', sa.Float(), nullable=True),
    sa.Column('extras_number', sa.Integer(), nullable=True),
    sa.Column('fastest_extras', sa.Float(), nullable=True),
    sa.Column('average_main', sa.Float(), nullable=True),
    sa.Column('slowest_main', sa.Float(), nullable=True),
    sa.Column('median_main', sa.Float(), nullable=True),
    sa.Column('main_number', sa.Integer(), nullable=True),
    sa.Column('fastest_main', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_game_title'), ['game_title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_game_title'))

    op.drop_table('games')
    # ### end Alembic commands ###
