"""likes

Revision ID: 30171c6cbcb2
Revises: 0c40f8170647
Create Date: 2024-04-02 19:03:19.781372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30171c6cbcb2'
down_revision = '0c40f8170647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
