"""empty message

Revision ID: 312ea1a7bf5c
Revises: b4f1def887c0
Create Date: 2024-03-14 10:33:15.642401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312ea1a7bf5c'
down_revision = 'b4f1def887c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_bio', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('pronouns', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('skill_level', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('availability')
        batch_op.drop_column('grade')
        batch_op.drop_column('role')
        batch_op.drop_column('skill_level')
        batch_op.drop_column('pronouns')
        batch_op.drop_column('user_bio')

    # ### end Alembic commands ###
