"""game table changes

Revision ID: 3b80158c9c29
Revises: b6f7ff3fb542
Create Date: 2024-03-18 13:42:38.586287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b80158c9c29'
down_revision = 'b6f7ff3fb542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('publisher', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('global_sales', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_games_genre'), ['genre'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_global_sales'), ['global_sales'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_publisher'), ['publisher'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_year'), ['year'], unique=False)
        batch_op.drop_column('average_extras')
        batch_op.drop_column('slowest_time')
        batch_op.drop_column('licensed')
        batch_op.drop_column('console')
        batch_op.drop_column('fastest_time')
        batch_op.drop_column('fastest_extras')
        batch_op.drop_column('slowest_extras')
        batch_op.drop_column('online')
        batch_op.drop_column('sales')
        batch_op.drop_column('publishers')
        batch_op.drop_column('release_year')
        batch_op.drop_column('median_extras')
        batch_op.drop_column('finish_number')
        batch_op.drop_column('fastest_completion')
        batch_op.drop_column('extras_number')
        batch_op.drop_column('median_time')
        batch_op.drop_column('sequel')
        batch_op.drop_column('max_players')
        batch_op.drop_column('age_rating')
        batch_op.drop_column('average_time')
        batch_op.drop_column('used_price')
        batch_op.drop_column('median_main')
        batch_op.drop_column('average_main')
        batch_op.drop_column('main_number')
        batch_op.drop_column('handheld')
        batch_op.drop_column('re_release')
        batch_op.drop_column('multiplatform')
        batch_op.drop_column('completion_number')
        batch_op.drop_column('genres')
        batch_op.drop_column('average_completion')
        batch_op.drop_column('median_completion')
        batch_op.drop_column('slowest_main')
        batch_op.drop_column('fastest_main')
        batch_op.drop_column('review_score')
        batch_op.drop_column('slowest_completion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slowest_completion', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('review_score', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('fastest_main', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('slowest_main', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('median_completion', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('average_completion', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('genres', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('completion_number', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('multiplatform', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('re_release', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('handheld', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('main_number', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('average_main', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('median_main', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('used_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('average_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('age_rating', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('max_players', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('sequel', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('median_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('extras_number', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('fastest_completion', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('finish_number', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('median_extras', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('release_year', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('publishers', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('sales', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('online', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('slowest_extras', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('fastest_extras', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('fastest_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('console', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('licensed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('slowest_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('average_extras', sa.FLOAT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_games_year'))
        batch_op.drop_index(batch_op.f('ix_games_publisher'))
        batch_op.drop_index(batch_op.f('ix_games_platform'))
        batch_op.drop_index(batch_op.f('ix_games_global_sales'))
        batch_op.drop_index(batch_op.f('ix_games_genre'))
        batch_op.drop_column('global_sales')
        batch_op.drop_column('publisher')
        batch_op.drop_column('genre')
        batch_op.drop_column('year')
        batch_op.drop_column('platform')

    # ### end Alembic commands ###
