"""post likes table

Revision ID: 47ecbc893292
Revises: 30171c6cbcb2
Create Date: 2024-04-02 19:12:29.438171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ecbc893292'
down_revision = '30171c6cbcb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_likes',
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('like_user_id', sa.Integer(), nullable=False),
    sa.Column('like_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['like_post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['like_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    with op.batch_alter_table('user_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_likes_like_id'), ['like_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_likes_like_id'))

    op.drop_table('user_likes')
    # ### end Alembic commands ###
