"""changed like table name

Revision ID: 58084bfe8449
Revises: 47ecbc893292
Create Date: 2024-04-02 19:13:48.790953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58084bfe8449'
down_revision = '47ecbc893292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('like_user_id', sa.Integer(), nullable=False),
    sa.Column('like_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['like_post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['like_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_likes_like_id'), ['like_id'], unique=True)

    with op.batch_alter_table('user_likes', schema=None) as batch_op:
        batch_op.drop_index('ix_user_likes_like_id')

    op.drop_table('user_likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_likes',
    sa.Column('like_id', sa.INTEGER(), nullable=False),
    sa.Column('like_user_id', sa.INTEGER(), nullable=False),
    sa.Column('like_post_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['like_post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['like_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    with op.batch_alter_table('user_likes', schema=None) as batch_op:
        batch_op.create_index('ix_user_likes_like_id', ['like_id'], unique=False)

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_likes_like_id'))

    op.drop_table('likes')
    # ### end Alembic commands ###
