"""tournaments table

Revision ID: 612e8fb95265
Revises: 58084bfe8449
Create Date: 2024-04-02 19:40:59.593699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612e8fb95265'
down_revision = '58084bfe8449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('tournament_name', sa.String(length=64), nullable=True),
    sa.Column('tournament_description', sa.String(length=140), nullable=True),
    sa.Column('tournament_start', sa.DateTime(), nullable=True),
    sa.Column('tournament_end', sa.DateTime(), nullable=True),
    sa.Column('tournament_skill_level', sa.String(length=64), nullable=True),
    sa.Column('tournament_min_grade', sa.String(length=64), nullable=True),
    sa.Column('tournament_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('tournament_id')
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournaments_tournament_end'), ['tournament_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_tournament_id'), ['tournament_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tournaments_tournament_name'), ['tournament_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_tournaments_tournament_start'), ['tournament_start'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournaments_tournament_start'))
        batch_op.drop_index(batch_op.f('ix_tournaments_tournament_name'))
        batch_op.drop_index(batch_op.f('ix_tournaments_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_tournaments_tournament_end'))

    op.drop_table('tournaments')
    # ### end Alembic commands ###
