"""readding EVERYTHING.

Revision ID: 99b0d65dac1f
Revises: 
Create Date: 2024-04-22 16:46:05.990101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b0d65dac1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('game_title', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('publisher', sa.String(length=64), nullable=True),
    sa.Column('global_sales', sa.Float(), nullable=True),
    sa.Column('sales_ranking', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_game_id'), ['game_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_games_game_title'), ['game_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_genre'), ['genre'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_global_sales'), ['global_sales'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_publisher'), ['publisher'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_sales_ranking'), ['sales_ranking'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_year'), ['year'], unique=False)

    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('pfp', sa.String(length=140), nullable=True),
    sa.Column('user_bio', sa.String(length=140), nullable=True),
    sa.Column('pronouns', sa.String(length=64), nullable=True),
    sa.Column('skill_level', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('grade', sa.String(length=64), nullable=True),
    sa.Column('availability', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('favourite_games',
    sa.Column('favourite_id', sa.Integer(), nullable=False),
    sa.Column('favourite_user_id', sa.Integer(), nullable=False),
    sa.Column('favourite_game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favourite_game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['favourite_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('favourite_id')
    )
    with op.batch_alter_table('favourite_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favourite_games_favourite_id'), ['favourite_id'], unique=True)

    op.create_table('following',
    sa.Column('follow_id', sa.Integer(), nullable=False),
    sa.Column('follow_user_id', sa.Integer(), nullable=False),
    sa.Column('follow_following_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follow_following_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['follow_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('follow_id')
    )
    with op.batch_alter_table('following', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_following_follow_id'), ['follow_id'], unique=True)

    op.create_table('posts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('post_title', sa.String(length=64), nullable=False),
    sa.Column('post_content', sa.String(length=140), nullable=False),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.Column('post_type', sa.String(length=64), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('post_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_post_id'), ['post_id'], unique=True)

    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=64), nullable=True),
    sa.Column('team_description', sa.String(length=140), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('availability', sa.String(length=140), nullable=True),
    sa.Column('skill_level', sa.String(length=64), nullable=True),
    sa.Column('fk_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_admin_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_team_id'), ['team_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_teams_team_name'), ['team_name'], unique=True)

    op.create_table('tournaments',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('tournament_name', sa.String(length=64), nullable=True),
    sa.Column('tournament_description', sa.String(length=140), nullable=True),
    sa.Column('tournament_start', sa.DateTime(), nullable=True),
    sa.Column('tournament_end', sa.DateTime(), nullable=True),
    sa.Column('tournament_skill_level', sa.String(length=64), nullable=True),
    sa.Column('tournament_min_grade', sa.String(length=64), nullable=True),
    sa.Column('tournament_user_id', sa.Integer(), nullable=True),
    sa.Column('participants', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('tournament_id')
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournaments_tournament_end'), ['tournament_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_tournament_id'), ['tournament_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tournaments_tournament_name'), ['tournament_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_tournaments_tournament_start'), ['tournament_start'], unique=False)

    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('comment_content', sa.String(length=140), nullable=False),
    sa.Column('comment_date', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('comment_user_id', sa.Integer(), nullable=False),
    sa.Column('comment_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['comment_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_comment_date'), ['comment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_comment_id'), ['comment_id'], unique=True)

    op.create_table('likes',
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('like_user_id', sa.Integer(), nullable=False),
    sa.Column('like_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['like_post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['like_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_likes_like_id'), ['like_id'], unique=True)

    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('round_match', sa.Integer(), nullable=False),
    sa.Column('match_winner_id', sa.Integer(), nullable=True),
    sa.Column('match_tournament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_tournament_id'], ['tournaments.tournament_id'], ),
    sa.ForeignKeyConstraint(['match_winner_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_match_date'), ['match_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_match_id'), ['match_id'], unique=True)

    op.create_table('practises',
    sa.Column('practise_id', sa.Integer(), nullable=False),
    sa.Column('practise_date', sa.Date(), nullable=False),
    sa.Column('practise_time', sa.Time(), nullable=False),
    sa.Column('practise_name', sa.String(length=64), nullable=True),
    sa.Column('practise_description', sa.String(length=140), nullable=True),
    sa.Column('practise_team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['practise_team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('practise_id')
    )
    with op.batch_alter_table('practises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practises_practise_date'), ['practise_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_practises_practise_id'), ['practise_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_practises_practise_name'), ['practise_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_practises_practise_time'), ['practise_time'], unique=False)

    op.create_table('team_users',
    sa.Column('team_user_id', sa.Integer(), nullable=False),
    sa.Column('fk_team_id', sa.Integer(), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('team_user_id')
    )
    with op.batch_alter_table('team_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_users_team_user_id'), ['team_user_id'], unique=True)

    op.create_table('tournament_users',
    sa.Column('tournament_user_id', sa.Integer(), nullable=False),
    sa.Column('tournament_tournament_id', sa.Integer(), nullable=False),
    sa.Column('tournament_user_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_tournament_id'], ['tournaments.tournament_id'], ),
    sa.ForeignKeyConstraint(['tournament_user_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('tournament_user_id')
    )
    with op.batch_alter_table('tournament_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_users_tournament_user_id'), ['tournament_user_id'], unique=True)

    op.create_table('match_users',
    sa.Column('matchuser_id', sa.Integer(), nullable=False),
    sa.Column('match_user_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['match_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('matchuser_id')
    )
    with op.batch_alter_table('match_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_users_matchuser_id'), ['matchuser_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_users_matchuser_id'))

    op.drop_table('match_users')
    with op.batch_alter_table('tournament_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_users_tournament_user_id'))

    op.drop_table('tournament_users')
    with op.batch_alter_table('team_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_users_team_user_id'))

    op.drop_table('team_users')
    with op.batch_alter_table('practises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practises_practise_time'))
        batch_op.drop_index(batch_op.f('ix_practises_practise_name'))
        batch_op.drop_index(batch_op.f('ix_practises_practise_id'))
        batch_op.drop_index(batch_op.f('ix_practises_practise_date'))

    op.drop_table('practises')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_match_id'))
        batch_op.drop_index(batch_op.f('ix_matches_match_date'))

    op.drop_table('matches')
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_likes_like_id'))

    op.drop_table('likes')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_comment_id'))
        batch_op.drop_index(batch_op.f('ix_comments_comment_date'))

    op.drop_table('comments')
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournaments_tournament_start'))
        batch_op.drop_index(batch_op.f('ix_tournaments_tournament_name'))
        batch_op.drop_index(batch_op.f('ix_tournaments_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_tournaments_tournament_end'))

    op.drop_table('tournaments')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_team_name'))
        batch_op.drop_index(batch_op.f('ix_teams_team_id'))

    op.drop_table('teams')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_post_id'))

    op.drop_table('posts')
    with op.batch_alter_table('following', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_following_follow_id'))

    op.drop_table('following')
    with op.batch_alter_table('favourite_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favourite_games_favourite_id'))

    op.drop_table('favourite_games')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_year'))
        batch_op.drop_index(batch_op.f('ix_games_sales_ranking'))
        batch_op.drop_index(batch_op.f('ix_games_publisher'))
        batch_op.drop_index(batch_op.f('ix_games_platform'))
        batch_op.drop_index(batch_op.f('ix_games_global_sales'))
        batch_op.drop_index(batch_op.f('ix_games_genre'))
        batch_op.drop_index(batch_op.f('ix_games_game_title'))
        batch_op.drop_index(batch_op.f('ix_games_game_id'))

    op.drop_table('games')
    # ### end Alembic commands ###
