"""empty message

Revision ID: b4f1def887c0
Revises: 9cbe4ea5c425
Create Date: 2024-03-14 09:56:11.258851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f1def887c0'
down_revision = '9cbe4ea5c425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('availability')
        batch_op.drop_column('role')
        batch_op.drop_column('skill_level')
        batch_op.drop_column('grade')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('pronouns')
        batch_op.drop_column('user_bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_bio', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('pronouns', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('skill_level', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.VARCHAR(length=140), nullable=True))

    # ### end Alembic commands ###
