"""game table changes p2

Revision ID: c188f1df00d0
Revises: 3b80158c9c29
Create Date: 2024-03-18 13:51:07.650078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c188f1df00d0'
down_revision = '3b80158c9c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_ranking', sa.Integer(), nullable=True))
        batch_op.alter_column('game_title',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_games_game_id'), ['game_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_games_sales_ranking'), ['sales_ranking'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_sales_ranking'))
        batch_op.drop_index(batch_op.f('ix_games_game_id'))
        batch_op.alter_column('game_title',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('sales_ranking')

    # ### end Alembic commands ###
