"""match users table

Revision ID: c4cfdf70986a
Revises: 2ccb0edea123
Create Date: 2024-04-17 09:14:07.696181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cfdf70986a'
down_revision = '2ccb0edea123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_users',
    sa.Column('matchuser_id', sa.Integer(), nullable=False),
    sa.Column('match_user_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['match_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('matchuser_id')
    )
    with op.batch_alter_table('match_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_users_matchuser_id'), ['matchuser_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_users_matchuser_id'))

    op.drop_table('match_users')
    # ### end Alembic commands ###
