"""tournament users

Revision ID: d72b579ff6a0
Revises: ea872c007fc7
Create Date: 2024-04-07 19:37:46.009921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd72b579ff6a0'
down_revision = 'ea872c007fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_users',
    sa.Column('tournament_user_id', sa.Integer(), nullable=False),
    sa.Column('tournament_tournament_id', sa.Integer(), nullable=False),
    sa.Column('tournament_user_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_tournament_id'], ['tournaments.tournament_id'], ),
    sa.ForeignKeyConstraint(['tournament_user_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('tournament_user_id')
    )
    with op.batch_alter_table('tournament_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_users_tournament_user_id'), ['tournament_user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_users_tournament_user_id'))

    op.drop_table('tournament_users')
    # ### end Alembic commands ###
