"""comments table

Revision ID: e1e9c755ef77
Revises: d72b579ff6a0
Create Date: 2024-04-07 19:58:56.970255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e9c755ef77'
down_revision = 'd72b579ff6a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('comment_content', sa.String(length=140), nullable=False),
    sa.Column('comment_date', sa.DateTime(), nullable=False),
    sa.Column('comment_user_id', sa.Integer(), nullable=False),
    sa.Column('comment_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['comment_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_comment_date'), ['comment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_comment_id'), ['comment_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_comment_id'))
        batch_op.drop_index(batch_op.f('ix_comments_comment_date'))

    op.drop_table('comments')
    # ### end Alembic commands ###
