"""sponsored users table

Revision ID: f4eda139a487
Revises: 99b0d65dac1f
Create Date: 2024-05-14 13:39:41.216837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4eda139a487'
down_revision = '99b0d65dac1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsored_users',
    sa.Column('sponsored_user_id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('sponsored_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['sponsored_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('sponsored_user_id')
    )
    with op.batch_alter_table('sponsored_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sponsored_users_sponsored_user_id'), ['sponsored_user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsored_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsored_users_sponsored_user_id'))

    op.drop_table('sponsored_users')
    # ### end Alembic commands ###
