"""posts table

Revision ID: f989f99b5421
Revises: b96b3fc2ba78
Create Date: 2024-03-31 20:39:17.282685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f989f99b5421'
down_revision = 'b96b3fc2ba78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('post_title', sa.String(length=64), nullable=False),
    sa.Column('post_content', sa.String(length=140), nullable=False),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.Column('post_type', sa.String(length=64), nullable=True),
    sa.Column('post_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_post_date'), ['post_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_post_id'), ['post_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_posts_post_title'), ['post_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_post_type'), ['post_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_post_type'))
        batch_op.drop_index(batch_op.f('ix_posts_post_title'))
        batch_op.drop_index(batch_op.f('ix_posts_post_id'))
        batch_op.drop_index(batch_op.f('ix_posts_post_date'))

    op.drop_table('posts')
    # ### end Alembic commands ###
